version: '3.6'
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: catalog

  vault2:
    image: vault
    container_name: vault
    cap_add:
      - IPC_LOCK
    volumes:
      - './vault-config/config:/config'
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 934f9eae-31ff-a8ef-e1ca-4bea9e07aa09
      VAULT_ADDR: 'http://0.0.0.0:8200'
      VAULT_TOKEN: 934f9eae-31ff-a8ef-e1ca-4bea9e07aa09
      VAULT_DEV_TOKEN: 934f9eae-31ff-a8ef-e1ca-4bea9e07aa09
    ports:
      - "8200:8200"
    command: ['config/vault-init.sh']
      